### ISSUE TITLE
Critical error exporting textures

### ISSUE THREAD

**Issue by KryptonCaptain** [blueyu2/Strata#3]
Tried to run the export textures command, so I can change some things with a resource pack, and it outputs this in the log for every ore added in configs, for each depth state
Obviouly, the problem is that it's trying to add an invalid character in the filename, the |

[16:08:57] [Client thread/INFO]: Unable to output strata:thermalfoundation/**ore/ore_silver.0+minecraft|stone**
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.io.File.createNewFile(Unknown Source)
**[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at com.blueyu2.strata.CommandClientOutputTextures.func_71515_b(CommandClientOutputTextures.java:69)**
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraftforge.client.ClientCommandHandler.func_71556_a(ClientCommandHandler.java:72)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.client.gui.GuiChat.func_146403_a(GuiChat.java:141)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.client.gui.GuiChat.func_73869_a(GuiChat.java:131)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:319)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.client.Minecraft.func_71407_l(Unknown Source)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.client.Minecraft.func_71411_J(Unknown Source)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.client.main.Main.main(SourceFile:148)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.lang.reflect.Method.invoke(Unknown Source)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at java.lang.reflect.Method.invoke(Unknown Source)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[16:08:57] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by KryptonCaptain** [comment]
Fixed this at my end by changing the output filename gen
